config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'authentications#create'
  resources :users, except: %i[new]
  resources :sessions, except: %i[index edit update show new destroy]
  resources :friendships
  resources :gratitude_items do
    resources :reflections
  end
  resources :password_resets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about' => 'sites#about'
  # Defines the root path route ("/")
  root 'sites#index'
end

app/models/gratitude_item.rb
class GratitudeItem < ApplicationRecord
  has_many :reflections
  belongs_to :user
  validates :name, presence: true

end

app/controllers/gratitude_items_controller.rb
class GratitudeItemsController < ApplicationController
  before_action :authenticate
  before_action :load_gratitude_item, except: [:new, :index, :create]
  # GET /gratitude_items
  def index
    @gratitude_items = current_user.gratitude_items
  end

  # GET /gratitude_items/new
  def new
    @gratitude_item = GratitudeItem.new
  end

  # POST /gratitude_items
  def create
    @gratitude_item = GratitudeItem.new gratitude_item_params
    @gratitude_item.user = current_user
    if @gratitude_item.save
      redirect_to gratitude_items_path, notice: "Gratitude Created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /gratitude_items/:id
  def show; end

  # GET /gratitude_items/:id/edit
  def edit; end

  # PATCH/PUT /gratitude_items/:id
  def update
    if @gratitude_item.update gratitude_item_params
      redirect_to @gratitude_item, notice: "Gratitude was Updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /gratitude_items/:id
  def destroy
    @gratitude_item.destroy
    redirect_to gratitude_items_path, alert: "Gratitude was Deleted"
  end

  private

  def load_gratitude_item
    @gratitude_item = current_user.gratitude_items.find params[:id]
  end

  def gratitude_item_params
    params.require(:gratitude_item).permit(:name,:date,:details,:friend_id)
  end
end

app/helpers/gratitude_items_helper.rb
module GratitudeItemsHelper
end

app/views/gratitude_items/_form.html.erb
<%= form_with(model: @gratitude_item) do |form| %>
  <div id="flash-messages">
      <% @gratitude_item.errors.full_messages.each do |msg| %>
        <div class="alert alert-error shadow-lg my-2" data-controller="alert" data-alert-animation-class="transition duration-500 ease-in-out transform opacity-0">
          <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          <span><%= msg %></span>
          </div>
        </div>
      <% end %> 
  </div>
  <div class="form-control w-full max-w-xs">
    <label class="label">
      <span class="label-text">Gratitude Name:</span>
    </label>
    <%= form.text_field :name, class: "input input-bordered input-primary w-full max-w-xs", placeholder: "Type here"%>
  </div>
  <div class="form-control w-full max-w-xs">
    <label class="label">
      <span class="label-text">Date:</span>
    </label>
  <%= form.date_field :date, value: Date.today, disabled: false, class: "input input-bordered input-primary w-full max-w-xs" %>
  </div>
  <div class="form-control w-full max-w-xs">
    <label class="label">
      <span class="label-text">Details:</span>
    </label>
  <%= form.text_area :details, placeholder: "Details", class: "textarea textarea-primary w-full max-w-xs" %>
  </div>
  <div class="form-control w-full max-w-xs">
    <label class="label">
      <span class="label-text">Friend:</span>
    </label>
    <%= form.collection_select(:friend_id, User.find(current_user.friendships.map(&:friend_id)),:id, :name, {:include_blank => 'Choose a Friend'}, class: "select select-ghost select-primary w-full max-w-xs") %>
  </div>
  <%= form.submit class: "btn btn-secondary mt-2"%>
<% end %>

app/views/gratitude_items/_gratitude_item.html.erb
<div id="<%= dom_id(gratitude_item) %>" class="card w-1/3 bg-secondary shadow-xl my-2">
    <div class="card-body">
        <h2 class="card-title"><%= link_to_unless_current gratitude_item.name, gratitude_item %></h2>
        <p><%= gratitude_item.details %></p>
        <p><%= gratitude_item.date %></p>
        <% if gratitude_item.friend_id %>
          <p>Friend - <%= User.find(gratitude_item.friend_id).name %></p>
        <% end %>
    </div>
</div>

app/views/gratitude_items/edit.html.erb
<%= title "Edit Gratitude" %>

<%= render 'form' %>

app/views/gratitude_items/index.html.erb
<% title "Gratitudes" %>

<% @gratitude_items.each do |gratitude_item| %>
  <%= render gratitude_item %>
<% end %>

<p>
<%= link_to "New Gratitude", new_gratitude_item_path, class: "btn btn_primary my-2" %>
</p>

app/views/gratitude_items/new.html.erb
<% title "Create Gratitude" %>

<%= render 'form' %>

app/views/gratitude_items/show.html.erb
<% title "View Gratitude" %>

<%= render @gratitude_item %>

<div class="flex flex-row gap-2">
    <%= link_to "<- All Gratitudes", gratitude_items_path, class: "btn btn-primary"%>
    <%= link_to "Show Reflections", gratitude_item_reflections_path(@gratitude_item), class: "btn btn-primary"%>
    <%= link_to "Edit Gratitude", edit_gratitude_item_path(@gratitude_item), class: "btn btn-primary"%>
    <%= button_to "Delete Gratitude", @gratitude_item, method: :delete, class: "btn btn-error", form: { data: {turbo_confirm: "Are you sure? "}}%>
</div>