config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'authentications#create'
  resources :users, except: %i[new]
  resources :sessions, except: %i[index edit update show new destroy]
  resources :friendships
  resources :gratitude_items do
    resources :reflections
  end
  resources :password_resets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about' => 'sites#about'
  # Defines the root path route ("/")
  root 'sites#index'
end

app/models/reflection.rb
class Reflection < ApplicationRecord
  belongs_to :gratitude_item

  validates :reflection_date, presence: true
  validates :title, presence: true
end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController
  before_action :authenticate
  before_action :load_gratitude_item
  before_action :load_reflection, except: %i[index new create]

  def index; end

  def new
    @reflection = Reflection.new
  end

  def create
    @reflection = Reflection.new reflection_params
    if @gratitude_item.reflections << @reflection
      redirect_to gratitude_item_reflections_path(@gratitude_item), notice: 'Reflection Created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @reflection.update reflection_params
      redirect_to gratitude_item_reflections_path(@gratitude_item), notice: 'Reflection Updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reflection.destroy
    redirect_to gratitude_item_reflections_path(@gratitude_item), alert: 'Reflection Deleted.'
  end

  private

  def reflection_params
    params.require(:reflection).permit(:body, :reflection_date, :title)
  end

  def load_gratitude_item
    @gratitude_item = current_user.gratitude_items.find params[:gratitude_item_id]
  end

  def load_reflection
    @reflection = @gratitude_item.reflections.find params[:id]
  end
end

app/helpers/reflections_helper.rb
module ReflectionsHelper
end

app/views/reflections/_form.html.erb
<%= form_with(model: [@gratitude_item,@reflection]) do |form| %>
  <div id="flash-messages">
      <% @reflection.errors.full_messages.each do |msg| %>
        <div class="alert alert-error shadow-lg my-2" data-controller="alert" data-alert-animation-class="transition duration-500 ease-in-out transform opacity-0">
          <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          <span><%= msg %></span>
          </div>
        </div>
      <% end %> 
  </div>
  <div class="form-control w-full max-w-xs">
    <label class="label">
      <span class="label-text">Reflection Name:</span>
    </label>
    <%= form.text_field :title, class: "input input-bordered input-primary w-full max-w-xs", placeholder: "Type here"%>
  </div>
  <div class="form-control w-full max-w-xs">
    <label class="label">
      <span class="label-text">Date:</span>
    </label>
  <%= form.date_field :reflection_date, value: Date.today, disabled: false, class: "input input-bordered input-primary w-full max-w-xs" %>
  </div>
  <div class="form-control w-full max-w-xs">
    <label class="label">
      <span class="label-text">Details:</span>
    </label>
  <%= form.text_area :body, placeholder: "Reflection", class: "textarea textarea-primary w-full max-w-xs" %>
  </div>
  <%= form.submit class: "btn btn-secondary mt-2"%>
<% end %>

app/views/reflections/_reflection.html.erb
  <div id="<%= dom_id(reflection) %>" class="card w-full lg:w-1/3 bg-secondary shadow-xl my-2">
      <div class="card-body">
        <h2 class="card-title"><%= reflection.title %></h2>
        <p><%= reflection.body %></p>
        <p><%= reflection.reflection_date %></p>
        <div class="card-actions justify-end">
            <%= link_to "Edit Reflection", edit_gratitude_item_reflection_path(@gratitude_item,reflection), class: "btn btn-primary my-2"%>
            <%= button_to "Delete Reflection", [@gratitude_item,reflection], method: :delete, class: "btn btn-error my-2", form: { data: { turbo_confirm: "Are you sure? " } } %>
        </div>
    </div>
  </div>

app/views/reflections/edit.html.erb
<% title "Edit Reflection" %>

<%= render 'form' %>

app/views/reflections/index.html.erb
<% title "Reflections for "+ @gratitude_item.name %>

<%= render @gratitude_item.reflections %>

<p>
  <%= link_to "<- Back to Gratitude", gratitude_item_path(@gratitude_item), class: "btn btn_primary my-2" %>
  <%= link_to "New Reflection", new_gratitude_item_reflection_path(@gratitude_item), class: "btn btn_primary my-2" %>
</p>

app/views/reflections/new.html.erb
<% title "New Reflection" %>

<%= render 'form' %>

app/views/reflections/show.html.erb
<%= title "Reflection for "+@reflection.gratitude_item.name %>

<%= render @reflection %>