config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'authentications#create'
  resources :users, except: %i[new]
  resources :sessions, except: %i[index edit update show new destroy]
  resources :friendships
  resources :gratitude_items do
    resources :reflections
  end
  resources :password_resets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about' => 'sites#about'
  # Defines the root path route ("/")
  root 'sites#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :friend_id, presence: true
end

app/models/gratitude_item.rb
class GratitudeItem < ApplicationRecord
  has_many :reflections
  belongs_to :user
  validates :name, presence: true

end

app/models/reflection.rb
class Reflection < ApplicationRecord
  belongs_to :gratitude_item

  validates :reflection_date, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :old_password

  has_secure_password
  has_many :gratitude_items
  has_many :friendships

  validates :name, presence: true
  validates :email, format: { with: /@/, message: 'Must have an @' }, uniqueness: true

  before_create { generate_token(:auth_token) }

  def self.new_from_hash(user_hash)
    user = User.new user_hash
    user.password_digest = 0
    user
  end

  def has_password?
    password_digest.nil? || password_digest != '0'
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  
  def authenticate
    if !current_user
      session[:protected_page] = request.url
      redirect_to login_path, alert: "User must be logged in to view page."
    end
  end

  def login(user)
    if params[:remember_me]
      cookies.permanent[:auth_token] = user.auth_token
    else
      cookies[:auth_token] = user.auth_token
    end
  end

  def logout
    cookies.delete(:auth_token)
  end

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate

  def create
    @friendship = Friendship.new friendship_params
    if @friendship.save
      redirect_to users_path, notice: 'Friended'
    else
      redirect_to users_path, status: :unprocessable_entity
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy
    redirect_to users_path, notice: 'Unfriended'
  end

  private

  def friendship_params
    params.permit(:user_id, :friend_id)
  end
end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController
  before_action :authenticate
  before_action :load_gratitude_item
  before_action :load_reflection, except: %i[index new create]

  def index; end

  def new
    @reflection = Reflection.new
  end

  def create
    @reflection = Reflection.new reflection_params
    if @gratitude_item.reflections << @reflection
      redirect_to gratitude_item_reflections_path(@gratitude_item), notice: 'Reflection Created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @reflection.update reflection_params
      redirect_to gratitude_item_reflections_path(@gratitude_item), notice: 'Reflection Updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reflection.destroy
    redirect_to gratitude_item_reflections_path(@gratitude_item), alert: 'Reflection Deleted.'
  end

  private

  def reflection_params
    params.require(:reflection).permit(:body, :reflection_date, :title)
  end

  def load_gratitude_item
    @gratitude_item = current_user.gratitude_items.find params[:gratitude_item_id]
  end

  def load_reflection
    @reflection = @gratitude_item.reflections.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.where(email: params[:email]).first
    if @user && @user.authenticate(params[:password])
      login(@user)
      page_to_redirect_to = session[:protected_page] || root_path
      session[:protected_page] = nil
      redirect_to page_to_redirect_to, notice: 'Logged in'
    else
      redirect_to login_path, alert: 'Invalid Email or Password'
    end
  rescue BCrypt::Errors::InvalidHash
    redirect_to login_path, alert: "Invalid password, did you signup with Github?"
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
  end
  
  def about
    flash.now[:notice] = "This is a notice"
    flash.now[:alert] = "This is an alert"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: %i[new create]
  before_action :load_current_user, except: %i[new create show index]

  def index
    @users = User.all.reject { |u| u.id == current_user.id }
  end

  def new
    if session[:user_hash]
      @user = User.new_from_hash session[:user_hash]
      @user.valid?
    else
      @user = User.new
    end
  end

  def create
    if session[:user_hash]
      @user = User.new_from_hash session[:user_hash]
      @user.name = user_params[:name]
      @user.email = user_params[:email]
    else
      @user = User.new user_params
    end
    if @user.save
      login(@user)
      session[:user_hash] = nil
      redirect_to root_path, notice: 'You signed up!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = if current_user.id == params[:id].to_i
              current_user
            else
              User.find_by_id(params[:id])
            end
  end

  def edit; end

  def update
    if @user.has_password? && !@user.authenticate(user_params[:old_password])
      render :edit, status: :unauthorized
      return
    end
    if @user.update user_params
      redirect_to user_path(@user), notice: 'User updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    @user.destroy
    redirect_to root_path, alert: 'User account deleted'
  end

  private

  def load_current_user
    if current_user.id == params[:id].to_i
      @user = current_user
    else
      redirect_to root_path, alert: 'Unauthorized'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :old_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/gratitude_items_helper.rb
module GratitudeItemsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/reflections_helper.rb
module ReflectionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
  
    def title(name,show_title = true)
        @show_title = show_title
        content_for(:title) do
            name
        end
    end
  
    def nav_link(text, path)
        if current_page?(path)
            content_tag :li do
                link_to(text, path, class: "active")
            end
        else
            content_tag :li do
                link_to(text, path)
            end
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gratitude<%= " | "+yield(:title) unless yield(:title).blank? %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- BEGIN NAVBAR -->
    <div class="navbar bg-base-300">
      <div class="flex-1">
        <ul class="menu menu-horizontal p-0">
          <%= nav_link 'Home', root_path %>
          <% if current_user %>
            <%= nav_link 'Gratitudes', gratitude_items_path %>
            <%= nav_link 'Users', users_path %>
          <% end %>
          <%= nav_link 'About', about_path %>
        </ul>
      </div>
      <div class="flex-none">
        <ul class="menu menu-horizontal p-0">
          <% if current_user %>
            <%= nav_link current_user.name, user_path(current_user) %>
            <%= nav_link 'Logout', logout_path %>
          <% else %>
            <%= nav_link 'Login', login_path %>
            <%= nav_link 'Sign Up', signup_path %>
          <% end %>
        </ul>
      </div>
    </div>
    <!-- END NAVBAR -->
    <main class="mx-4 mt-4 flex flex-col">
      <!-- ALERT FLASH MESSAGES -->
      <div id="flash-messages">
      <% flash.each do |name, msg| %>
        <div class="alert <%= name == 'notice' ? 'alert-info' : 'alert-error'%> shadow-lg mb-2" data-controller="alert" data-alert-animation-class="transition duration-500 ease-in-out transform opacity-0">
          <div>
          <% if name == 'notice' %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          <% end %>
          <span><%= msg %></span>
          </div>
          <div class="flex-none">
            <button class="btn btn-sm btn-ghost" data-action="click->alert#close">Dismiss</button>
          </div>
        </div>
      <% end %> 
      </div>
      <% if @show_title %>
        <h1 class="font-bold text-4xl"> <%= yield(:title) %></h1>
      <% end %>
      <!-- END FLASH MESSAGES -->
      <%= yield %>
    </main>
  </body>
</html>